# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
"""
Графический интерфейс плеера
"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap, QFont


class Ui_MainWindow(object):
    def __init__(self):
        self.time = None
        self.next_song_button = None
        self.previous_song_button = None
        self.pause_button = None
        self.name_song = None
        self.image_song = None
        self.playlists = None
        self.time_slider = None
        self.remove_playlist_button = None
        self.add_playlist_button = None
        self.add_song_button = None
        self.remove_song_button = None
        self.playlist_label = None
        self.songs_label = None
        self.songs = None
        self.centralwidget = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QIcon("icons/player.png"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # Окно с песнями
        self.songs = QtWidgets.QListWidget(self.centralwidget)
        self.songs.setGeometry(QtCore.QRect(30, 80, 341, 271))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        self.songs.setFont(font)
        self.songs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.songs.setAutoFillBackground(False)
        self.songs.setDragEnabled(True)
        self.songs.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.songs.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.songs.setProperty("isWrapping", False)
        self.songs.setResizeMode(QtWidgets.QListView.Adjust)
        self.songs.setWordWrap(False)
        self.songs.setSelectionRectVisible(False)
        self.songs.setObjectName("songs")
        # Текст Песни
        self.songs_label = QtWidgets.QLabel(self.centralwidget)
        self.songs_label.setGeometry(QtCore.QRect(70, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.songs_label.setFont(font)
        self.songs_label.setObjectName("songs_label")
        # Текст Плейлист
        self.playlist_label = QtWidgets.QLabel(self.centralwidget)
        self.playlist_label.setGeometry(QtCore.QRect(450, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_label.setFont(font)
        self.playlist_label.setObjectName("playlist_label")
        # Окно с плейлистами
        self.playlists = QtWidgets.QListWidget(self.centralwidget)
        self.playlists.setGeometry(QtCore.QRect(420, 80, 351, 271))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        self.playlists.setFont(font)
        self.playlists.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playlists.setDragEnabled(True)
        self.playlists.setDragDropOverwriteMode(False)
        self.playlists.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.playlists.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.playlists.setIconSize(QtCore.QSize(0, 0))
        self.playlists.setResizeMode(QtWidgets.QListView.Adjust)
        self.playlists.setSelectionRectVisible(False)
        self.playlists.setObjectName("playlists")
        # Кнопка Убрать песню
        self.remove_song_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_song_button.setGeometry(QtCore.QRect(290, 30, 41, 31))
        self.remove_song_button.setObjectName("remove_song_button")
        # Кнопка Добавить песню
        self.add_song_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_song_button.setGeometry(QtCore.QRect(220, 30, 41, 31))
        self.add_song_button.setObjectName("add_song_button")
        # Кнопка Добавить плейлист
        self.add_playlist_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_playlist_button.setGeometry(QtCore.QRect(620, 30, 41, 31))
        self.add_playlist_button.setObjectName("add_playlist_button")
        # Кнопка Удалить плейлист
        self.remove_playlist_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_playlist_button.setGeometry(QtCore.QRect(690, 30, 41, 31))
        self.remove_playlist_button.setObjectName("remove_playlist_button")
        # Виджет проигрывания трека
        self.time_slider = QtWidgets.QSlider(self.centralwidget)
        self.time_slider.setGeometry(QtCore.QRect(70, 480, 691, 31))
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setStyleSheet(
            """
            QSlider::groove:horizontal {
                border: 2px solid #fcfaef;
                height: 10px;
                background: #FFFFFF;
                border-radius: 4px;
            }
            QSlider::handle:horizontal {
                background: #121212;
                width: 12px;
                height: 8px;
                border-radius: 4px;
            }
            """
        )
        self.time_slider.setObjectName("time_slider")
        # Картинка песни
        self.image_song = QtWidgets.QLabel(self.centralwidget)
        self.image_song.setGeometry(QtCore.QRect(360, 360, 81, 81))
        self.image_song.setObjectName("image_song")
        # Текст песни
        self.name_song = QtWidgets.QLabel(self.centralwidget)
        self.name_song.setGeometry(QtCore.QRect(100, 450, 561, 20))
        font = QFont()
        font.setFamily("System")
        font.setPointSize(10)
        font.setBold(False)
        self.name_song.setFont(font)
        self.name_song.setObjectName("name_song")
        # Кнопка паузы
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(370, 520, 51, 41))
        self.pause_button.setIcon(QIcon("icons/play.png"))
        self.pause_button.setObjectName("pause_button")
        # Кнопка предыдущая песня
        self.previous_song_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_song_button.setGeometry(QtCore.QRect(300, 520, 51, 41))
        self.previous_song_button.setIcon(QIcon("icons/previous.png"))
        self.previous_song_button.setObjectName("previous_song_button")
        # Кнопка следующая песня
        self.next_song_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_song_button.setGeometry(QtCore.QRect(440, 520, 51, 41))
        self.next_song_button.setIcon(QIcon("icons/next.png"))
        self.next_song_button.setObjectName("next_song_button")
        # Таймер
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(704, 449, 51, 21))
        font = QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        self.time.setObjectName("time")
        self.time.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music Player"))
        self.playlist_label.setText(_translate("MainWindow", "Плейлисты"))
        self.songs_label.setText(_translate("MainWindow", "Песни"))
        self.remove_song_button.setText(_translate("MainWindow", "-"))
        self.add_song_button.setText(_translate("MainWindow", "+"))
        self.add_playlist_button.setText(_translate("MainWindow", "+"))
        self.remove_playlist_button.setText(_translate("MainWindow", "-"))
